#Download base image PHP along with apache server
FROM php:7.4.3-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql 

RUN apt-get update -y && apt-get install -y git curl libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev \
    libfreetype6-dev
RUN apt-get update && \
    apt-get install -y \
        zlib1g-dev nano

RUN apt-get install -y libzip-dev 
RUN docker-php-ext-install zip gd
    
RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

WORKDIR /var/www/html/v1
# COPY ./composer.json .
# RUN composer install

COPY . .



