version: '3'
services:
  web:
    container_name: web_server 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - db
    volumes:
      - /var/www/html/inspektechProjects/v1:/var/www/html/v1
    ports:
      - "8080:80"
  
  db:
    container_name: mysql_server
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME} 
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./bridgenew_db:/docker-entrypoint-initdb.d
    ports:
        - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME} 
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:80"
